POST http://localhost:6007/api/phonebill/total/
Content-Type: application/json

    {
    "bill" : "sms,call,sms,call,sms,call" 
}


####

GET http://localhost:6007/api/phonebill/prices/
Content-Type: application/json

####

POST http://localhost:6007/api/phonebill/price/
Content-Type: application/json

{
    "type": "sms",
    "price": 1.25
}

####

POST http://localhost:6007/api/phonebill/price/
Content-Type: application/json

{
    "type": "call",
    "price": 0.25
}